import { MODEL_FILES, type ModelFile } from "@/lib/model-index";
import type { SystemId } from "@/types/content";

/**
 * Registry of 3D models and their licences (Section 13), used by the credits
 * page. GLBs are generated by `npm run models`; mesh node names match
 * `BodyPart.meshName`. See public/models/ATTRIBUTION.txt.
 */
export interface ModelEntry {
  id: ModelFile;
  system: SystemId | "whole-body";
  style: "cartoon" | "semi-realistic" | "realistic" | "schematic";
  source: "placeholder" | "glb";
  /** Path under /public, e.g. "/models/skeleton.<hash>.glb" (GLB sources only). */
  url?: string;
  licence: string;
  attribution?: string;
  sourceUrl?: string;
}

const BODYPARTS3D = {
  source: "glb",
  style: "realistic",
  licence: "CC BY-SA 2.1 JP",
  attribution: "BodyParts3D, © The Database Center for Life Science",
  sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/",
} as const;

const FILE_SYSTEMS: Record<ModelFile, ModelEntry["system"]> = {
  skin: "integumentary",
  skeleton: "skeletal",
  muscles: "muscular",
  organs: "whole-body",
  circulatory: "circulatory",
};

export const MODEL_REGISTRY: readonly ModelEntry[] = (Object.keys(MODEL_FILES) as ModelFile[]).map((id) => ({
  id,
  system: FILE_SYSTEMS[id],
  url: MODEL_FILES[id],
  ...BODYPARTS3D,
}));
